<a href="https://colab.research.google.com/github/23jiwon/pytorch_deeplearning/blob/main/1_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1강. 타입, 라이브러리

파이썬(python)은 데이터 분석 분야에서 매우 널리 쓰이는 프로그래밍 언어 중 하나다. <br>머신러닝, 딥러닝에  관련된 라이브러리가 매우 많고 적용이 쉽기 때문이다.

## 1.1 타입<br>
타입은 모든 프로그래밍 언어에서 가장 중요한 개념이자 기본이다. 또한 타입에 따라 성질이 다르기 때문에 항상 조심해야 하는 부분이다. 우리가 사용하는 모든 것들은 특정 타입을 가지고 있다. 예를 들어 정수형, 실수형, 문자형, 리스트, 배열 등이 있는데 우리가 만든 연산에서 타입 맞지 않으면 원하는 결괄르 얻을 수 없다.

In [2]:
# 원하는 값을 출력하기
print("DeepLearning Bro!")

DeepLearning Bro!


### 1.1.1 int

In [3]:
a=1 # 메모리할당
b=0
c=-1

# 타입 확인하기
print(a, type(a))
print(b, type(b))
print(c, type(c))

1 <class 'int'>
0 <class 'int'>
-1 <class 'int'>


In [4]:
# a+b 표현하기
d=a+b
print(d)

1


In [5]:
print(a+b)

1


### 1.1.2 float

In [6]:
a=1.2
b=2.4
c=0. #숫자 뒤에 .을 붙이면 실수형으로 인식
d=.5 #0.5 의미

In [7]:
# 부동 소수점의 문제
print(a+b) 

3.5999999999999996


2진수로 계산한 후 10진수로 결과를 표현하기 때문에 발생하는 문제

In [ ]:
print(a, type(a))
print(b, type(b))
print(c, type(c))

### 1.1.3 str

In [9]:
a = 'deep '
b = 'learning'
print(type(a), type(b))

<class 'str'> <class 'str'>


In [10]:
# str 의 덧셈
print(a+b) #덧셈만 가능. 문자를 붙여주는 역할

deeplearning


### 1.1.4 bool

In [11]:
# True and False
a=True
b=False
print(type(a), type(b))

<class 'bool'> <class 'bool'>


### 1.1.5 주의하기

In [12]:
# 숫자형 문자
a=1
b='1'
print(a)
print(b)

1
1


In [13]:
# 간혹 데이터가 숫자처럼 보이지만 문자인 경우들이 있다. 오류에 당황하지 말고 타입을 살펴본다.

In [14]:
#str을 int로 변환
c = int(b)
d = float(b) #실수형으로 변환

### 1.1.6 리스트

In [23]:
# list
list1 = [1,2,3,4]
print(list1, type(list1))

[1, 2, 3, 4] <class 'list'>


타입에 따라서 함수 사용과 연산이 달라질 수 있기 때문에 list등의 모임도 타입을 확인해야 한다.

In [19]:
# element
print(list1[0])
print(list1[:2]) #0~2(즉, 0,1 번째 출력)

1
[1, 2]


### 1.1.7 튜플

튜플은 변경 불가

In [20]:
# tuple
a = (1,2)
print(a,type(a))
print(a[0])

(1, 2) <class 'tuple'>
1


In [24]:
list1[1] = 100 #리스트는 변경가능

In [22]:
a[1] = 100 #튜플은 변경 불가

TypeError: ignored

### 1.1.8 딕셔너리

In [25]:
# dict
a={"class" : ['deep learning', 'machine learning'], "students" : [40,20]}
print(a)

{'class': ['deep learning', 'machine learning'], 'students': [40, 20]}


In [26]:
print(type(a))

<class 'dict'>


In [27]:
print(a["class"])

['deep learning', 'machine learning']


In [28]:
print(a["class"][0])

deep learning


### 1.1.9 Numpy 배열

In [29]:
import numpy #행렬 연산에 특화된 library

arr = numpy.array([1,2,3,4]) # numpy 중에서 array 함수 사용
print(arr,type(arr))

[1 2 3 4] <class 'numpy.ndarray'>


이 밖에 set, Tensor, DataFrame, Series, PIL Image 등 다양한 타입이 존재.

## 1.2 라이브러리
import를 통해 미리 만들어 놓은 함수와 클래스를 쉽게 사용할 수 있으며 다양한 라이브러리들이 존재한다.

In [31]:
# numpy는 다양한 연산을 제공하며 데이터 분석에 있어 가장 기본이 되는 라이브러리 중 하나다.

import numpy as np #약자로 사용 가능

arr = np.array([1,2,3,4])
print(arr, type(arr))

[1 2 3 4] <class 'numpy.ndarray'>


In [33]:
# numpy 내 특정 함수만 불러오기
from numpy import array, ones, zeros

# 이렇게 불러오면 함수만 지정하면 된다.
a = array([1,2,3,4])
b = ones(5) # 1짜리
c = zeros((5,2))

In [34]:
print(a)
print(b) #기본적으로 실수형으로 생성되는 듯
print(c)

[1 2 3 4]
[1. 1. 1. 1. 1.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


# 2강. 조건문, 반복문<br>
조건문과 반복문은 모든 프로그래밍 언어에서 필수로 알아야 할 내용이다. 조건 반복문을 통해 우리가 우너하는 규칙을 구현할 수 있다.

In [35]:
import numpy as np

## 2.1 조건문

In [36]:
x = 10
if x== 1:
  print("x=1")
else:
  print("x!=1")

x!=1


In [38]:
x = 10

if x==1:
  print("x는 1입니다")
elif x==2: #조건이 여러 개인 경우 elif 사용
  print("x는 2입니다.")
elif x==3:
  print("x는 3입니다.")
else:
  print("x는 4입니다.")

# 경우의 수를 잘 생각해서 코드를 잘 짜야 한다. 이 예시는 잘못된 코드임

x는 4입니다.


## 2.2 반복문

In [39]:
for i in range(5): # range(5) : [0,1,2,3,4]
  print(i)

0
1
2
3
4


In [40]:
i=0
while i<5:
  print(i)
  i+=1

0
1
2
3
4


## 2.3 예시

### 2.3.1 이차방정식의 실근의 개수

In [45]:
# ax^2 + bx + c = 0
# [a.b.c] 라고 표현
f = np.random.randint(10, size=(10,3)) #10*3 짜리 행렬
print(f)

[[0 1 9]
 [0 0 6]
 [0 2 7]
 [9 0 8]
 [7 1 0]
 [5 5 3]
 [1 4 5]
 [2 6 8]
 [0 8 9]
 [2 2 5]]


In [46]:
for g in f:
  if g[0] == 0:
    print("이차 방정식이 아닙니다.");
  else:
    D = g[1]**2 - 4*g[0]*g[2]
    if D ==0:
      print("서로 같은 두 실근")
    elif D>0 :
      print("서로 다른 두 실근");
    else:
      print("서로 다른 두 허근")

이차 방정식이 아닙니다.
이차 방정식이 아닙니다.
이차 방정식이 아닙니다.
서로 다른 두 허근
서로 다른 두 실근
서로 다른 두 허근
서로 다른 두 허근
서로 다른 두 허근
이차 방정식이 아닙니다.
서로 다른 두 허근


### 2.3.2 break문 

In [47]:
pending = [1,3,5,3,8,1,4,5]

In [49]:
# 짝수가 나오면 바로 종료
for i in pending:
  if i%2 == 0:
    print(i,'는 짝수입니다')
    break

8 는 짝수입니다


### 2.3.3 type-expect 문<br>
원치 않은 데이터가 들어온 상황에서 배제하고자 할 때 사용

In [50]:
x = [1,2,3,"s", 4,5]

for i in x:
  try:
    y=i+1
    print(y)
  except:
    print(i, "는 오류입니다.")

2
3
4
s 는 오류입니다.
5
6


# 3강. 함수

코딩을 하다 보면 동일한 연산을 자주 사용하거나 문장이 길어지는 논리가 있을 수 있다. 이 때 우리는 함수 하나를 정희해 코드를 쉽게 알아 볼 수 있게 하고 필요할 때마다 편리하게 미리 정의된 함수를 불러와서 사용할 수 있다. <br>
***보통 함수는 소문자로 시작하고 class는 대문자로 시작***

## 3.1 음수 개수 판독기

In [51]:
def negative(arr):
  count = len(np.where(arr<0)[0])
  print(f"해당 배열 안에는 음수가 {count}개 있습니다.")

where : 위치 인덱스 반환하는 함수

In [52]:
arr1 = np.array([0,-2,-3, -5, -6])
arr2 = np.array([0,2,3,5,6])

In [56]:
np.where(arr1<0)

(array([1, 2, 3, 4]),)

In [57]:
np.where(arr1<0)[0]

array([1, 2, 3, 4])

In [58]:
len(np.where(arr1<0)[0])

4

In [53]:
negative(arr1)
negative(arr2)

해당 배열 안에는 음수가 4개 있습니다.
해당 배열 안에는 음수가 0개 있습니다.


## 3.2 목적 함수 정의

In [59]:
def objective_function(x):
  return np.sin(x)+np.cos(x) + .f*np.exp(x)

SyntaxError: ignored