<a href="https://colab.research.google.com/github/23jiwon/pytorch_deeplearning/blob/main/introduction_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 텐서
텐서(Tensor)는 파이토치의 기본 단위이며 GPU 연산을 가능하게 한다. 또한 Numpy의 배열과 유사하여 손쉽게 다룰 수 있다.

## 1.1 텐서 만들기

In [1]:
# 라이브러기 불러오기
import torch # pytorch를 사용하기 위한 기본 라이브러리이다.
import numpy as np

In [2]:
# 빈 텐서 생성
x = torch.empty(5,4) #5행 4열 행렬 생성
print(x) # 초기화되지 않은 행렬인 경우 해당 시점에 할당된 메모리에 존재하던 값들이 초기값으로 나타난다.

tensor([[1.2777e-35, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [3]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [4]:
torch.zeros(2)

tensor([0., 0.])

In [5]:
torch.rand(5,6)

tensor([[7.5116e-01, 2.5979e-01, 2.1700e-03, 8.8371e-01, 3.3724e-01, 6.6979e-01],
        [3.2113e-01, 5.6555e-01, 3.5464e-01, 9.3153e-01, 7.6244e-01, 2.0696e-01],
        [9.5577e-01, 8.2063e-01, 1.9772e-01, 6.9499e-05, 4.3750e-01, 7.6388e-01],
        [8.1090e-01, 4.6713e-01, 7.8854e-02, 7.4614e-01, 5.4135e-01, 7.2769e-02],
        [8.6310e-02, 9.8905e-01, 8.7798e-01, 3.3767e-01, 2.0299e-01, 6.2107e-01]])

## 1.2 리스트, 넘파이 배열을 텐서로 만들기

In [6]:
l = [13,4]
r = np.array([4,56,7]) # 넘파이 배열 생성

In [7]:
torch.tensor(l) # 리스트를 텐서로 쉽게 변환할 수 있다.

tensor([13,  4])

In [8]:
torch.tensor(r) #넘파이 배열을 텐서로 쉽게 변환할 수 있다.

tensor([ 4, 56,  7])

## 1.3 텐서의 크기와 타입 확인하기

In [9]:
x.size() # .size()는 텐서의 크기를 확인할 수 있으며 매우 자주 사용된다.

torch.Size([5, 4])

In [10]:
type(x) # type은 python에서 사용되는 모든 것들의 종류를 보여준다.

torch.Tensor

## 1.4 텐서의 덧셈

In [11]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.1962, 0.9634],
        [0.9813, 0.8289]])
tensor([[0.0575, 0.4885],
        [0.4553, 0.1869]])


In [12]:
x+y

tensor([[0.2537, 1.4518],
        [1.4366, 1.0158]])

In [13]:
torch.add(x,y)

tensor([[0.2537, 1.4518],
        [1.4366, 1.0158]])

In [14]:
y.add(x) # 두 텐서의 합의 다른 표현. y에 x를 더한다는 의미

tensor([[0.2537, 1.4518],
        [1.4366, 1.0158]])

In [15]:
print("원래 y : ", y)
y.add_(x)
print("y=y+x : ",y)

# y.add_는 y에 x를 더한 값을 y에 대체한다.(inplace 방식)

원래 y :  tensor([[0.0575, 0.4885],
        [0.4553, 0.1869]])
y=y+x :  tensor([[0.2537, 1.4518],
        [1.4366, 1.0158]])


## 1.5 텐서의 크기 변환하기